name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile Java
        run: javac -d bin src/*.java

      - name: Run Tests
        run: java -cp bin:tests/* org.junit.platform.console.ConsoleLauncher --scan-classpath