name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile Java code
        run: javac -d ./compiled ./src/*.java

      - name: Install JUnit 5
        run: |
          curl -L -o junit-platform-console-standalone.jar https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.0/junit-platform-console-standalone-1.8.0.jar

      - name: Compile and Run Tests
        run: |
          javac -cp .:tests -d . tests/*.java
          java -cp .:tests org.junit.runner.JUnitCore $(find tests -name "*Test.class" | sed 's/\.class$//' | sed 's/\//./g')