name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile Java code
        run: javac -d ./compiled ./src/*.java

      - name: Download JUnit JAR
        run: curl -O https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar

      - name: Compile and Run Tests
        run: |
          javac -cp .:tests -d . tests/*.java
          java -cp .:tests org.junit.runner.JUnitCore $(find tests -name "*Test.class" | sed 's/\.class$//' | sed 's/\//./g')